FROM python:3.11-alpine
RUN apk add postgresql-dev

WORKDIR /app

COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./ .

CMD ["uvicorn", "main:app", "--host" ,"0.0.0.0" ,"--reload"]
